import TickIconSvg from "./TickIconSvg";
import PlusSvg from "./PlusSvg";
import ClassroomSvg from "./ClassroomSvg";
import LeftChevron from "./LeftChevron";
import LeftChevronSvg from "./LeftChevronSvg";
import RightChevronSvg from "./RightChevronSvg";
import CollageIconSvg from "./CollageIconSvg";
import FileIconSvg from "./FileIconSvg";
import LinkIconSvg from "./LinkIconSvg";
import LikeFillSvg from "./LikeFillSvg";
import LikeEmptySvg from "./LikeEmptySvg";
import SmileSvg from "./SmileSvg";
import NoteIconSvg from "./NoteIconSvg";
import PhotoIconSvg from "./PhotoIconSvg";
import VideoIconSvg from "./VideoIconSvg";
import FilterIconSvg from "./FilterIconSvg";
import FilterIconNewSvg from "./FilterIconNewSvg";
import ActivityIconSvg from "./ActivityIconSvg";
import JournalIconSvg from "./JournalIconSvg";
import MessagesIconSvg from "./MessagesIconSvg";
import MoreIconSvg from "./MoreIconSvg";
import DrawerIconSvg from "./DrawerIconSvg";
import MoreItemIconSvg from "./MoreItemIconSvg";
import StudentIconSvg from "./StudentIconSvg";
import CommentIconSvg from "./CommentIconSvg";
import LikeIconSvg from "./LikeIconSvg";
import AllStudentsIconSvg from "./AllStudentsIconSvg";
import CloseIconSvg from "./CloseIconSvg";
import VideoRecordSvg from "./VideoRecordSvg";
import AllMediaIconSvg from "./AllMediaIconSvg";
import VideoPlayButton from "./VideoPlayButton";
import RecordStart from "./RecordStart";
import RecordStop from "./RecordStop";
import PhotoClickButton from "./PhotoClickButton";
import GalleryButton from "./GalleryButton";
import SwitchCameraMode from "./SwitchCameraMode";
import VideoPlayIconSvg from "./VideoPlayIconSvg";
import PdfSvg from "./PdfSvg";
import RadioOnSvg from "./RadioOnSvg";
import SquareTickSvg from "./SquareTickSvgSelected";
import SquareTickSvgUnselected from "./SquareTickSvgUnselected";
import RadioOffSvg from "./RadioOffSvg";
import OpenFullScreenSvg from "./OpenFullScreenSvg";
import CloseFullScreenSvg from "./CloseFullScreenSvg";
import BookSvg from "./BookSvg";
import EditIconSvg from "./EditIconSvg";
import AddWithCircleSvg from "./AddWithCircleSvg";
import CalendarSvg from "./CalendarSvg";
import AttendanceSvg from "./AttendanceSvg";
import SignOutSvg from "./SignOutSvg";
import SettingSvgIcon from "./SettingSvgIcon";
import SendInvitationIcon from "./SendInvitationIcon";
import UserProfileImagePlaceholder from "./UserProfileImagePlaceholder";
import InviteFamilySvg from "./InviteFamilySvg";
import NoCommentSvg from "./NoCommentSvg";
import DeleteIconSvg from "./DeleteIconSvg";
import RetrySvg from "./RetrySvg";
import CrossSvg from "./CrossSvg";
import TagStudentsIcon from "./TagStudentsIcon";
import TagActivityIcon from "./TagActivityIcon";
import TagSkillsIcon from "./TagSkillsIcon";
import SearchSvg from "./SearchSvg";
import ArrowIcon from "./ArrowIcon";
import PublishSvg from "./PublishSvg";
import EditSvg from "./EditSvg";
import ToddleIcon from "./ToddleIcon";
import PlayIcon from "./PlayIcon";
import PdfLineIcon from "./PdfLineIcon";
import ExpandIcon from "./ExpandIcon";
import CheckboxView from "./CheckboxView";
import EvidenceIconSvg from "./EvidenceIconSvg";
import PortfolioIconSvg from "./PortfolioIconSvg";
import ViewIconSvg from "./ViewIconSvg";
import CheckboxOnSvg from "./CheckboxOnSvg.js";
import CheckboxOffSvg from "./CheckboxOffSvg.js";
import DragIconSvg from "./DragIconSvg";
import PinchIconSvg from "./PinchIconSvg";
import UserFilterIconSvg from "./UserFilterIconSvg";

exports.CheckboxView = CheckboxView;
exports.ExpandIcon = ExpandIcon;
exports.PdfLineIcon = PdfLineIcon;
exports.PlayIcon = PlayIcon;
exports.ToddleIcon = ToddleIcon;
exports.ArrowIcon = ArrowIcon;
exports.PlusSvg = PlusSvg;
exports.TickIconSvg = TickIconSvg;
exports.ClassroomSvg = ClassroomSvg;
exports.LeftChevron = LeftChevron;
exports.RightChevronSvg = RightChevronSvg;
exports.LeftChevronSvg = LeftChevronSvg;
exports.CollageIconSvg = CollageIconSvg;
exports.FileIconSvg = FileIconSvg;
exports.LinkIconSvg = LinkIconSvg;
exports.NoteIconSvg = NoteIconSvg;
exports.PhotoIconSvg = PhotoIconSvg;
exports.VideoIconSvg = VideoIconSvg;
exports.FilterIconSvg = FilterIconSvg;
exports.ActivityIconSvg = ActivityIconSvg;
exports.JournalIconSvg = JournalIconSvg;
exports.MessagesIconSvg = MessagesIconSvg;
exports.MoreIconSvg = MoreIconSvg;
exports.DrawerIconSvg = DrawerIconSvg;
exports.MoreItemIconSvg = MoreItemIconSvg;
exports.StudentIconSvg = StudentIconSvg;
exports.CommentIconSvg = CommentIconSvg;
exports.LikeIconSvg = LikeIconSvg;
exports.LikeEmptySvg = LikeEmptySvg;
exports.LikeFillSvg = LikeFillSvg;
exports.AllStudentsIconSvg = AllStudentsIconSvg;
exports.CloseIconSvg = CloseIconSvg;
exports.VideoRecordSvg = VideoRecordSvg;
exports.AllMediaIconSvg = AllMediaIconSvg;
exports.VideoPlayButton = VideoPlayButton;
exports.RecordStart = RecordStart;
exports.RecordStop = RecordStop;
exports.PhotoClickButton = PhotoClickButton;
exports.GalleryButton = GalleryButton;
exports.SwitchCameraMode = SwitchCameraMode;
exports.VideoPlayIconSvg = VideoPlayIconSvg;
exports.PdfSvg = PdfSvg;
exports.RadioOnSvg = RadioOnSvg;
exports.RadioOffSvg = RadioOffSvg;
exports.SquareTickSvg = SquareTickSvg;
exports.SquareTickSvgUnselected = SquareTickSvgUnselected;
exports.CloseFullScreenSvg = CloseFullScreenSvg;
exports.OpenFullScreenSvg = OpenFullScreenSvg;
exports.SmileSvg = SmileSvg;
exports.BookSvg = BookSvg;
exports.EditIconSvg = EditIconSvg;
exports.AddWithCircleSvg = AddWithCircleSvg;
exports.CalendarSvg = CalendarSvg;
exports.AttendanceSvg = AttendanceSvg;
exports.SignOutSvg = SignOutSvg;
exports.SettingSvgIcon = SettingSvgIcon;
exports.SendInvitationIcon = SendInvitationIcon;
exports.UserProfileImagePlaceholder = UserProfileImagePlaceholder;
exports.InviteFamilySvg = InviteFamilySvg;
exports.NoCommentSvg = NoCommentSvg;
exports.DeleteIconSvg = DeleteIconSvg;
exports.RetrySvg = RetrySvg;
exports.CrossSvg = CrossSvg;
exports.TagStudentsIcon = TagStudentsIcon;
exports.TagActivityIcon = TagActivityIcon;
exports.TagSkillsIcon = TagSkillsIcon;
exports.SearchSvg = SearchSvg;
exports.PublishSvg = PublishSvg;
exports.EditSvg = EditSvg;
exports.EvidenceIconSvg = EvidenceIconSvg;
exports.PortfolioIconSvg = PortfolioIconSvg;
exports.ViewIconSvg = ViewIconSvg;
exports.CheckboxOffSvg = CheckboxOffSvg;
exports.CheckboxOnSvg = CheckboxOnSvg;
exports.DragIconSvg = DragIconSvg;
exports.PinchIconSvg = PinchIconSvg;
exports.UserFilterIconSvg = UserFilterIconSvg;
exports.FilterIconNewSvg = FilterIconNewSvg;
